FROM tensorflow/tensorflow:latest-gpu


RUN apt-get update && apt-get install git


# git clone https://github.com/tensorflow/models
# move official out of models

RUN pip install pandas gin-config tensorflow-addons